title: 線上編輯地圖
author: Leo
logo: logo.png

only_build_toc_files: true
execute:
  execute_notebooks: "off"

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

exclude:
  - references.bib

repository:
  url: https://github.com/wendy062644/wendy062644-2025-summer-intern-project-1
  path_to_book: ""
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  thebe: false

sphinx:
  config:
    copyright: "2025 Yu-Lin Chen"
    html_extra_path: ["assets"]
    html_css_files:
      - book.css